/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CadastroView: typeof import('./src/components/telaCadastro/CadastroView.vue')['default']
    DialogView: typeof import('./src/components/dialog/DialogView.vue')['default']
    FormCadastroUser: typeof import('./src/components/forms/formCadastroUser.vue')['default']
    FormCompleteProfile: typeof import('./src/components/forms/formCompleteProfile.vue')['default']
    LandingPage: typeof import('./src/components/LandingPage.vue')['default']
    LandingPageAluno: typeof import('./src/components/Telaaluno/LandingPageAluno.vue')['default']
    LoginView: typeof import('./src/components/login/LoginView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBarView: typeof import('./src/components/snackBar/snackBarView.vue')['default']
  }
}
