/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LandingPage: typeof import('./src/components/LandingPage.vue')['default']
    LandingPageAluno: typeof import('./src/components/Telaaluno/LandingPageAluno.vue')['default']
    LoginView: typeof import('./src/components/login/LoginView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
